<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
<h1>{{ $details['name'] }}</h1>
<h1>{{ $details['email'] }}</h1>
<h1>{{ $details['body'] }}</h1>
    <p>Thank you </p>
</body>
</html> 